name: Terraform - AWS Control Tower (Manual Plan)

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    name: 'Terraform Init & Plan'
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: us-east-2

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 5.99.1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="variables.tfvars"
